name: deploy

on:
  push:
    tags: ["*"]

jobs:
  publish-assets:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Cache SBT
          uses: coursier/cache-action@v6
        - name: Java 11 setup
          uses: actions/setup-java@v4
          with:
            distribution: corretto
            java-version: 11
        - run: sbt assembly
        - name: Upload Jars
          uses: softprops/action-gh-release@v1
          with:
            draft: true
            files: |
              avro-tools/target/scala-2.13/avro-tools-*.jar
              magnolify-tools/target/scala-2.13/magnolify-tools-*.jar
              parquet-cli/target/scala-2.13/parquet-cli-*.jar
              proto-tools/target/scala-2.13/proto-tools-*.jar
